[build]
publish = "_site"

[build.environment]
NODE_VERSION = "16.13.0"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = false

[build.processing.images]
compress = true
